BrowserCreativeCrudBundle_CrudItem_index:
    pattern:  /
    defaults: { _controller: BrowserCreativeCrudBundle:CrudItem:index }

BrowserCreativeCrudBundle_CrudItem_new:
    pattern:  /new
    defaults: { _controller: BrowserCreativeCrudBundle:CrudItem:update }

BrowserCreativeCrudBundle_CrudItem_edit:
    pattern:  /edit/{itemId}
    defaults: { _controller: BrowserCreativeCrudBundle:CrudItem:update }
    requirements:
        itemId:  \d+

BrowserCreativeCrudBundle_CrudItem_delete:
    pattern:  /delete/{itemId}
    defaults: { _controller: BrowserCreativeCrudBundle:CrudItem:delete }
    requirements:
        itemId:  \d+

BrowserCreativeCrudBundle_CrudItem_view:
    pattern:  /{itemId}/{itemSubject}
    defaults: { _controller: BrowserCreativeCrudBundle:CrudItem:view }
    requirements:
        itemId:  \d+