parameters:
    hub_news.external_news_provider.class: BrowserCreative\CrudBundle\Service\ExternalCrudProvider

services:
    externalCrud.provider:
        class: %hub_news.external_news_provider.class%
        arguments: [@service_container]