parameters:
    browsercreative_crud.crud_provider.class: BrowserCreative\CrudBundle\Service\CrudProvider

services:
    crud.provider:
        class: %browsercreative_crud.crud_provider.class%
        arguments: [@service_container]