parameters:
    hub_news.external_news_provider.class: Hub\NewsBundle\Service\ExternalNewsProvider

services:
    externalNews.provider:
        class: %hub_news.external_news_provider.class%
        arguments: [@service_container]