<?php

namespace BrowserCreative\CrudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrudItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrudItemRepository extends EntityRepository
{
    public function getLatestActiveItems()
    {
        $queryBuilder = $this->createQueryBuilder('c')
            ->add('where', 'c.visible = :visible')
            ->add('orderBy', 'c.date_created DESC')
            ->setParameter('visible', true);

        return $queryBuilder;
    }
}